In [8]:
import xarray as xr
a=xr.open_zarr('/data/zzn/chaosbench/cma/cma/cma_full_1.5deg_20160101.zarr')

In [9]:
a

<xarray.Dataset>
Dimensions:     (latitude: 121, level: 10, longitude: 240, step: 45)
Coordinates:
  * latitude    (latitude) float64 90.0 88.5 87.0 85.5 ... -87.0 -88.5 -90.0
  * level       (level) float64 10.0 50.0 100.0 200.0 ... 850.0 925.0 1e+03
  * longitude   (longitude) float64 0.0 1.5 3.0 4.5 ... 354.0 355.5 357.0 358.5
  * step        (step) timedelta64[ns] 0 days 1 days 2 days ... 43 days 44 days
    time        datetime64[ns] ...
Data variables:
    number      int64 ...
    q           (step, level, latitude, longitude) float32 dask.array<chunksize=(12, 3, 61, 120), meta=np.ndarray>
    t           (step, level, latitude, longitude) float32 dask.array<chunksize=(12, 3, 61, 120), meta=np.ndarray>
    u           (step, level, latitude, longitude) float32 dask.array<chunksize=(12, 3, 61, 120), meta=np.ndarray>
    v           (step, level, latitude, longitude) float32 dask.array<chunksize=(12, 3, 61, 120), meta=np.ndarray>
    valid_time  (step) datetime64[ns] dask.array<chunksize=(45,), meta=np.ndarray>
    w           (step, level, latitude, longitude) float32 dask.array<chunksize=(12, 3, 61, 120), meta=np.ndarray>
    z           (step, level, latitude, longitude) float32 dask.array<chunksize=(12, 3, 61, 120), meta=np.ndarray>
Attributes:
    Conventions:             CF-1.7
    GRIB_centre:             babj
    GRIB_centreDescription:  Beijing
    GRIB_edition:            2
    GRIB_subCentre:          0
    history:                 2023-09-14T10:38 GRIB to CDM+CF via cfgrib-0.9.1...
    institution:             Beijing

In [2]:
a['sigma'].values

array([9.96258887e+03, 5.88405615e+03, 5.53348584e+03, 5.80386035e+03,
       5.06312158e+03, 3.32691772e+03, 2.11070972e+03, 1.44347583e+03,
       1.20152893e+03, 1.04356421e+03, 3.63606347e-07, 3.33824062e-07,
       5.63761830e-07, 2.17758934e-05, 1.61201358e-04, 1.03740452e-03,
       2.46746163e-03, 4.00180463e-03, 5.00174332e-03, 5.83049096e-03,
       1.29490871e+01, 1.02527800e+01, 1.22903023e+01, 7.00062656e+00,
       1.07091017e+01, 1.29927845e+01, 1.47622709e+01, 1.55359058e+01,
       1.59549265e+01, 1.69808617e+01, 2.55127430e+01, 1.53262882e+01,
       1.33861790e+01, 1.73303661e+01, 1.64081287e+01, 1.14707899e+01,
       8.82164288e+00, 7.81162834e+00, 7.50252867e+00, 5.82367945e+00,
       1.07335920e+01, 6.69580364e+00, 7.04500389e+00, 1.09888191e+01,
       1.19223843e+01, 8.19463921e+00, 6.19243431e+00, 5.58292055e+00,
       5.75816250e+00, 4.81405163e+00, 2.08457396e-03, 6.15753047e-03,
       1.41742975e-02, 4.84863557e-02, 8.81016105e-02, 1.29510090e-01,
      

In [3]:
import xarray as xr
b=xr.open_zarr('/data/zzn/S2S/climatology/climatology_pressure_level_old.zarr')
b['sigma'].values

array([9.96258887e+03, 5.88405615e+03, 5.53348584e+03, 5.80386035e+03,
       5.06312158e+03, 3.32691772e+03, 2.11070972e+03, 1.44347583e+03,
       1.20152893e+03, 1.04356421e+03, 3.63606347e-07, 3.33824062e-07,
       5.63761830e-07, 2.17758934e-05, 1.61201358e-04, 1.03740452e-03,
       2.46746163e-03, 4.00180463e-03, 5.00174332e-03, 5.83049096e-03,
       1.29490871e+01, 1.02527800e+01, 1.22903023e+01, 7.00062656e+00,
       1.07091017e+01, 1.29927845e+01, 1.47622709e+01, 1.55359058e+01,
       1.59549265e+01, 1.69808617e+01, 2.55127430e+01, 1.53262882e+01,
       1.33861790e+01, 1.73303661e+01, 1.64081287e+01, 1.14707899e+01,
       8.82164288e+00, 7.81162834e+00, 7.50252867e+00, 5.82367945e+00,
       1.07335920e+01, 6.69580364e+00, 7.04500389e+00, 1.09888191e+01,
       1.19223843e+01, 8.19463921e+00, 6.19243431e+00, 5.58292055e+00,
       5.75816250e+00, 4.81405163e+00, 2.08457396e-03, 6.15753047e-03,
       1.41742975e-02, 4.84863557e-02, 8.81016105e-02, 1.29510090e-01,
      

In [5]:
a['sigma'].values==b['sigma'].values

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [8]:
import xarray as xr
b=xr.open_zarr('/data/zzn/S2S/single_level/era5_single_full_0.5deg_19791001.zarr')

In [9]:
b

<xarray.Dataset>
Dimensions:                   (latitude: 361, longitude: 720)
Coordinates:
  * latitude                  (latitude) float32 90.0 89.5 89.0 ... -89.5 -90.0
  * longitude                 (longitude) float32 0.0 0.5 1.0 ... 359.0 359.5
    time                      datetime64[ns] ...
Data variables:
    10m_u_component_of_wind   (latitude, longitude) float32 dask.array<chunksize=(361, 720), meta=np.ndarray>
    10m_v_component_of_wind   (latitude, longitude) float32 dask.array<chunksize=(361, 720), meta=np.ndarray>
    2m_dewpoint_temperature   (latitude, longitude) float32 dask.array<chunksize=(361, 720), meta=np.ndarray>
    2m_temperature            (latitude, longitude) float32 dask.array<chunksize=(361, 720), meta=np.ndarray>
    mean_sea_level_pressure   (latitude, longitude) float32 dask.array<chunksize=(361, 720), meta=np.ndarray>
    sea_ice_cover             (latitude, longitude) float32 dask.array<chunksize=(361, 720), meta=np.ndarray>
    sea_surface_temperature   (latitude, longitude) float32 dask.array<chunksize=(361, 720), meta=np.ndarray>
    surface_pressure          (latitude, longitude) float32 dask.array<chunksize=(361, 720), meta=np.ndarray>
    total_precipitation_24hr  (latitude, longitude) float32 dask.array<chunksize=(361, 720), meta=np.ndarray>

In [10]:
merged_dataset = xr.merge([a, b])

In [11]:
merged_dataset

<xarray.Dataset>
Dimensions:                                              (latitude: 361,
                                                          longitude: 720)
Coordinates:
  * latitude                                             (latitude) float32 9...
  * longitude                                            (longitude) float32 ...
    time                                                 datetime64[ns] ...
Data variables: (12/16)
    ice_temperature_layer_1                              (latitude, longitude) float32 dask.array<chunksize=(361, 720), meta=np.ndarray>
    ice_temperature_layer_2                              (latitude, longitude) float32 dask.array<chunksize=(361, 720), meta=np.ndarray>
    ice_temperature_layer_3                              (latitude, longitude) float32 dask.array<chunksize=(361, 720), meta=np.ndarray>
    ice_temperature_layer_4                              (latitude, longitude) float32 dask.array<chunksize=(361, 720), meta=np.ndarray>
    significant_height_of_combined_wind_waves_and_swell  (latitude, longitude) float32 dask.array<chunksize=(361, 720), meta=np.ndarray>
    significant_height_of_total_swell                    (latitude, longitude) float32 dask.array<chunksize=(361, 720), meta=np.ndarray>
    ...                                                   ...
    2m_temperature                                       (latitude, longitude) float32 dask.array<chunksize=(361, 720), meta=np.ndarray>
    mean_sea_level_pressure                              (latitude, longitude) float32 dask.array<chunksize=(361, 720), meta=np.ndarray>
    sea_ice_cover                                        (latitude, longitude) float32 dask.array<chunksize=(361, 720), meta=np.ndarray>
    sea_surface_temperature                              (latitude, longitude) float32 dask.array<chunksize=(361, 720), meta=np.ndarray>
    surface_pressure                                     (latitude, longitude) float32 dask.array<chunksize=(361, 720), meta=np.ndarray>
    total_precipitation_24hr                             (latitude, longitude) float32 dask.array<chunksize=(361, 720), meta=np.ndarray>